### ISSUE TITLE
Complete Descriptors Of Warden Industry Focus Tree

### ISSUE THREAD

**Issue by RegaSaurus24** [SafeHouse-Studios/Foxhole-Conquest#27]
**IN ORDER TO COMPLETE THIS TASK:** Design document of the Warden industry focus tree must first be completed.
[Warden Focus Tree Design Document](https://docs.google.com/document/d/1nBrQorOAaVDKdAS-1GCK_uGADRjIHWgAxXIBYLZnBMk/edit?usp=sharing)

**IN ORDER TO COMPLETE THIS TASK:** Issue https://github.com/SafeHouse-Studios/Foxhole-Conquest/issues/24 must be completed.

**Task Details:** Add descriptors to all Warden industry focuses from the documentation, check for spelling and grammar errors as you go. Specifically the Industry section is the left section of the focus tree. Your job is to go through the focus document for the Warden Nation and ensure that all of the focuses within this left most section all have the correct descriptions as is listed in the "Full Warden Focus Tree Designs". You will as mentioned also proof read as you go for spelling and grammar errors and fix them as you go, although be careful not to over wright anything that could be a lore name rather than a misspelling, if unsure ask design leader.

**Documentation:** [Full Warden Focus Tree Designs](https://docs.google.com/document/d/1SKl4GcNm26qxHmSv5CZwRSjYSlV2vQap/edit)
[Layout Designs Of Full Warden Focus Tree](https://drive.google.com/file/d/13g094-fFBCz2B4QAgWp8MCZZXAoD28tB/view?usp=sharing)

**Tutorial:** [Basic Focus Tree Creation](https://www.youtube.com/watch?v=svFVLXzU2MQ&ab_channel=TheIronWorkshop)

**Comment by kosmik247** [comment]
Spellcheck complete. 
Two notes:
1. Some descriptors are larger than the text area, leading the description to be hidden behind the effect.
2. Language continuation - E.G using caliber (american spelling of calibre) but using aluminium (british spelling of aluminum)

**Comment by RegaSaurus24** [comment]
Answers:

1) A specified list of the focus descriptions that are over the limit has been made:
Port of Buckler sound
The port of whedon's row
Facilitate heavy arms plants
The elksford rail line
Endless foundries
Forges of red chapel

2) Spell checking should be completed to American spelling standards.

**Comment by Kosmik247** [comment]
Spell check- complete

To do:
Shorten the descriptors that exceed the maximum size

**Comment by Kosmik247** [comment]
Update comment ~

Obtain descriptors for:

- [ ] - Port of Buckler sound
- [ ] - The port of whedon's row
- [ ] - Facilitate heavy arms plants
- [ ] - The elksford rail line
- [ ] - Endless foundries
- [ ] - Forges of red chapel
