### ISSUE TITLE
Complete Main GFX Of Colonial Political Focus Tree

### ISSUE THREAD

**Issue by RegaSaurus24** [SafeHouse-Studios/Foxhole-Conquest#68]
**IN ORDER TO COMPLETE THIS TASK:** Issue #65 must be completed.

**IN ORDER TO COMPLETE THIS TASK:** Custom focus icons for all of the Colonial political tree will need to have been created.

**Task Details:** This task involved uploading the appropriate GFX from the our own libraries and assigning them to their focuses. The icons can be found at "Main Colonial Focus Icons" and the method of attaching them can be found in the tutorial video. The political tree is the tree in the center of the "Layout Designs Of Full Colonial Focus Tree" document.

**Documentation:** [Layout Designs Of Full Colonial Focus Tree](https://drive.google.com/file/d/1Ub7985haNfphJt16pfki2XhCCatnBh32/view?usp=sharing)
[Main Colonial Focus Icons](https://docs.google.com/document/d/1EuS-yvnH6l1r-l45CPTbGUQa5oUczuc__1L51WUL0C8/edit?usp=sharing)

**Tutorial:** [Basic Focus Tree Creation](https://www.youtube.com/watch?v=svFVLXzU2MQ&ab_channel=TheIronWorkshop)

**Comment by Kosmik247** [comment]
GFX Checklist:

- [ ] A Senate Divided
- [ ] Concessions To Labor Unions
- [ ] Prosecute Nobility
- [ ] Organize The Red Legion
- [ ] The Mesean Socialist Party
- [ ] The Colonial Socialist Party
- [ ] The Velian Socialist Party
- [ ] Legionnaire Mutanies
- [ ] No Compromise
- [ ] Prepare The Second Front
- [ ] Legionary Officers Cabal
- [ ] Contact Caovish Diplomats
- [ ] A Deal With The Devil
- [ ] Forsake The Legion
- [ ] Revolution's Dawn
- [ ] Enforce Decolonization
- [ ] The Great Commune
- [ ] A Failing Senate
- [ ] Reassess Colonial Rights
- [ ] Replace Democratic Senators
- [ ] Empower Legates
- [ ] Form The Opposition Coalition
- [ ] A Change In Course
- [ ] The Aquilia Party
- [ ] Appeal To Velian Imperators
- [ ] Reconciliation With The Colonies
- [ ] Secret Velian Arms Plants
- [ ] Select A New Caesar
- [ ] Form The Praetorian Guard
- [ ] Dawn Of The Velian Imperium
- [ ] Slay The Mesean Bear
- [ ] Veli Invicta
- [ ] Refuse Colonial Representation
- [ ] Mesean Fascist Movement
- [ ] Appeal To Velian Senators
- [ ] Embrace Populism
- [ ] Prepare Fascist Assault Divisions
- [ ] Suppress The Press
- [ ] Disband The Senate
- [ ] Subjugate Colonies
- [ ] The Veli-Mesean State
- [ ] Rebuild The Nation
- [ ] Offer Greater Representation to The Colonies
- [ ] Maintain The Status Quo
- [ ] Sow The Seeds of Caovish Democracy
- [ ] Fund Caovish Republican Partisans
- [ ] Establish The Technology Committee
- [ ] Construct The Colonial Institute Of Science
- [ ] Arsenal of Democracy
- [ ] Form The Republican Guard
- [ ] Establish NorthWestern Colonies
- [ ] Establish NorthEastern Colonies
- [ ] Expand the Senate
- [ ] At The Gates of Wheadon’s Row
- [ ] Fallback to the Bulwark
- [ ] Last Stand Protocol
- [ ] Legion Of Liberty
